apiVersion: orchestrator.entur.io/apps/v1
kind: GoogleCloudApplication
metadata:
  id: wayfare
  displayName: Wayfare
  name: wayfare
  owner: team-selgerintegrasjoner
spec:
  environments:
    - dev
    - tst
  repositories:
    - wayfare
  kubernetes:
    enabled: true
  auth0:
    internal:
      enabled: true
      type: m2m
  secretManager:
    enabled: true
