common:
  app: wayfare
  shortname: wayfare
  team: selgerintegrasjoner

  container:
    image: wayfare
    cpu: 0.2
    memory: 512
    memoryLimit: 512
    replicas: 1
    probes:
      enabled: true
      liveness:
        path: /health/liveness
      readiness:
        path: /health/readiness

  service:
    internalPort: 8080
    externalPort: 80

  ingress:
    enabled: true
    trafficType: public

  configmap:
    enabled: true

  secrets:
    wayfare-omsa:
      - CLIENT_ID
      - CLIENT_SECRET
    wayfare-login:
      - ENTUR_LOGIN_CLIENT_ID
      - ENTUR_LOGIN_CLIENT_SECRET
    wayfare-auth0-internal:
      - MNG_AUTH0_INT_HOST
      - MNG_AUTH0_INT_AUDIENCE
      - MNG_AUTH0_INT_CLIENT_ID
      - MNG_AUTH0_INT_CLIENT_SECRET
