/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapRouteImport } from './routes/map'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PaymentReturnRouteImport } from './routes/payment-return'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as CheckoutOfferIdRouteImport } from './routes/checkout/$offerId'
import { Route as SeatsOfferIdRouteImport } from './routes/seats/$offerId'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsPackageIdRouteImport } from './routes/tickets/$packageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOfferIdRoute = CheckoutOfferIdRouteImport.update({
  id: '/checkout/$offerId',
  path: '/checkout/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsOfferIdRoute = SeatsOfferIdRouteImport.update({
  id: '/seats/$offerId',
  path: '/seats/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsPackageIdRoute = TicketsPackageIdRouteImport.update({
  id: '/tickets/$packageId',
  path: '/tickets/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/offers': typeof OffersRoute
  '/payment-return': typeof PaymentReturnRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/trips': typeof TripsRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/seats/$offerId': typeof SeatsOfferIdRoute
  '/tickets/$packageId': typeof TicketsPackageIdRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/offers': typeof OffersRoute
  '/payment-return': typeof PaymentReturnRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/trips': typeof TripsRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/seats/$offerId': typeof SeatsOfferIdRoute
  '/tickets/$packageId': typeof TicketsPackageIdRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/offers': typeof OffersRoute
  '/payment-return': typeof PaymentReturnRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/trips': typeof TripsRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/seats/$offerId': typeof SeatsOfferIdRoute
  '/tickets/$packageId': typeof TicketsPackageIdRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/offers'
    | '/payment-return'
    | '/products'
    | '/settings'
    | '/trips'
    | '/checkout/$offerId'
    | '/seats/$offerId'
    | '/tickets/$packageId'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/offers'
    | '/payment-return'
    | '/products'
    | '/settings'
    | '/trips'
    | '/checkout/$offerId'
    | '/seats/$offerId'
    | '/tickets/$packageId'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/offers'
    | '/payment-return'
    | '/products'
    | '/settings'
    | '/trips'
    | '/checkout/$offerId'
    | '/seats/$offerId'
    | '/tickets/$packageId'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  OffersRoute: typeof OffersRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  TripsRoute: typeof TripsRoute
  CheckoutOfferIdRoute: typeof CheckoutOfferIdRoute
  SeatsOfferIdRoute: typeof SeatsOfferIdRoute
  TicketsPackageIdRoute: typeof TicketsPackageIdRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-return': {
      id: '/payment-return'
      path: '/payment-return'
      fullPath: '/payment-return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$offerId': {
      id: '/checkout/$offerId'
      path: '/checkout/$offerId'
      fullPath: '/checkout/$offerId'
      preLoaderRoute: typeof CheckoutOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats/$offerId': {
      id: '/seats/$offerId'
      path: '/seats/$offerId'
      fullPath: '/seats/$offerId'
      preLoaderRoute: typeof SeatsOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$packageId': {
      id: '/tickets/$packageId'
      path: '/tickets/$packageId'
      fullPath: '/tickets/$packageId'
      preLoaderRoute: typeof TicketsPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  OffersRoute: OffersRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  TripsRoute: TripsRoute,
  CheckoutOfferIdRoute: CheckoutOfferIdRoute,
  SeatsOfferIdRoute: SeatsOfferIdRoute,
  TicketsPackageIdRoute: TicketsPackageIdRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
