/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as MapRouteImport } from './routes/map'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PaymentReturnRouteImport } from './routes/payment-return'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as CheckoutOfferIdRouteImport } from './routes/checkout/$offerId'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsPackageIdIndexRouteImport } from './routes/tickets/$packageId/index'
import { Route as TicketsPackageIdCancelRouteImport } from './routes/tickets/$packageId/cancel'
import { Route as TicketsPackageIdRefundRouteImport } from './routes/tickets/$packageId/refund'
import { Route as TicketsPackageIdStartTimeRouteImport } from './routes/tickets/$packageId/start-time'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOfferIdRoute = CheckoutOfferIdRouteImport.update({
  id: '/checkout/$offerId',
  path: '/checkout/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsPackageIdIndexRoute = TicketsPackageIdIndexRouteImport.update({
  id: '/tickets/$packageId/',
  path: '/tickets/$packageId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsPackageIdCancelRoute = TicketsPackageIdCancelRouteImport.update({
  id: '/tickets/$packageId/cancel',
  path: '/tickets/$packageId/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsPackageIdRefundRoute = TicketsPackageIdRefundRouteImport.update({
  id: '/tickets/$packageId/refund',
  path: '/tickets/$packageId/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsPackageIdStartTimeRoute =
  TicketsPackageIdStartTimeRouteImport.update({
    id: '/tickets/$packageId/start-time',
    path: '/tickets/$packageId/start-time',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/map': typeof MapRoute
  '/offers': typeof OffersRoute
  '/payment-return': typeof PaymentReturnRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/trips': typeof TripsRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/tickets/': typeof TicketsIndexRoute
  '/tickets/$packageId/cancel': typeof TicketsPackageIdCancelRoute
  '/tickets/$packageId/refund': typeof TicketsPackageIdRefundRoute
  '/tickets/$packageId/start-time': typeof TicketsPackageIdStartTimeRoute
  '/tickets/$packageId/': typeof TicketsPackageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/map': typeof MapRoute
  '/offers': typeof OffersRoute
  '/payment-return': typeof PaymentReturnRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/trips': typeof TripsRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/tickets': typeof TicketsIndexRoute
  '/tickets/$packageId/cancel': typeof TicketsPackageIdCancelRoute
  '/tickets/$packageId/refund': typeof TicketsPackageIdRefundRoute
  '/tickets/$packageId/start-time': typeof TicketsPackageIdStartTimeRoute
  '/tickets/$packageId': typeof TicketsPackageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/map': typeof MapRoute
  '/offers': typeof OffersRoute
  '/payment-return': typeof PaymentReturnRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/trips': typeof TripsRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/tickets/': typeof TicketsIndexRoute
  '/tickets/$packageId/cancel': typeof TicketsPackageIdCancelRoute
  '/tickets/$packageId/refund': typeof TicketsPackageIdRefundRoute
  '/tickets/$packageId/start-time': typeof TicketsPackageIdStartTimeRoute
  '/tickets/$packageId/': typeof TicketsPackageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/map'
    | '/offers'
    | '/payment-return'
    | '/products'
    | '/settings'
    | '/trips'
    | '/checkout/$offerId'
    | '/tickets/'
    | '/tickets/$packageId/cancel'
    | '/tickets/$packageId/refund'
    | '/tickets/$packageId/start-time'
    | '/tickets/$packageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/map'
    | '/offers'
    | '/payment-return'
    | '/products'
    | '/settings'
    | '/trips'
    | '/checkout/$offerId'
    | '/tickets'
    | '/tickets/$packageId/cancel'
    | '/tickets/$packageId/refund'
    | '/tickets/$packageId/start-time'
    | '/tickets/$packageId'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/map'
    | '/offers'
    | '/payment-return'
    | '/products'
    | '/settings'
    | '/trips'
    | '/checkout/$offerId'
    | '/tickets/'
    | '/tickets/$packageId/cancel'
    | '/tickets/$packageId/refund'
    | '/tickets/$packageId/start-time'
    | '/tickets/$packageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  MapRoute: typeof MapRoute
  OffersRoute: typeof OffersRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  TripsRoute: typeof TripsRoute
  CheckoutOfferIdRoute: typeof CheckoutOfferIdRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  TicketsPackageIdCancelRoute: typeof TicketsPackageIdCancelRoute
  TicketsPackageIdRefundRoute: typeof TicketsPackageIdRefundRoute
  TicketsPackageIdStartTimeRoute: typeof TicketsPackageIdStartTimeRoute
  TicketsPackageIdIndexRoute: typeof TicketsPackageIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-return': {
      id: '/payment-return'
      path: '/payment-return'
      fullPath: '/payment-return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$offerId': {
      id: '/checkout/$offerId'
      path: '/checkout/$offerId'
      fullPath: '/checkout/$offerId'
      preLoaderRoute: typeof CheckoutOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$packageId/': {
      id: '/tickets/$packageId/'
      path: '/tickets/$packageId'
      fullPath: '/tickets/$packageId/'
      preLoaderRoute: typeof TicketsPackageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$packageId/cancel': {
      id: '/tickets/$packageId/cancel'
      path: '/tickets/$packageId/cancel'
      fullPath: '/tickets/$packageId/cancel'
      preLoaderRoute: typeof TicketsPackageIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$packageId/refund': {
      id: '/tickets/$packageId/refund'
      path: '/tickets/$packageId/refund'
      fullPath: '/tickets/$packageId/refund'
      preLoaderRoute: typeof TicketsPackageIdRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$packageId/start-time': {
      id: '/tickets/$packageId/start-time'
      path: '/tickets/$packageId/start-time'
      fullPath: '/tickets/$packageId/start-time'
      preLoaderRoute: typeof TicketsPackageIdStartTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  MapRoute: MapRoute,
  OffersRoute: OffersRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  TripsRoute: TripsRoute,
  CheckoutOfferIdRoute: CheckoutOfferIdRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  TicketsPackageIdCancelRoute: TicketsPackageIdCancelRoute,
  TicketsPackageIdRefundRoute: TicketsPackageIdRefundRoute,
  TicketsPackageIdStartTimeRoute: TicketsPackageIdStartTimeRoute,
  TicketsPackageIdIndexRoute: TicketsPackageIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
