/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PaymentReturnRouteImport } from './routes/payment-return'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsPackageIdRouteImport } from './routes/tickets/$packageId'
import { Route as CheckoutOfferIdRouteImport } from './routes/checkout/$offerId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsPackageIdRoute = TicketsPackageIdRouteImport.update({
  id: '/tickets/$packageId',
  path: '/tickets/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOfferIdRoute = CheckoutOfferIdRouteImport.update({
  id: '/checkout/$offerId',
  path: '/checkout/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offers': typeof OffersRoute
  '/payment-return': typeof PaymentReturnRoute
  '/settings': typeof SettingsRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/tickets/$packageId': typeof TicketsPackageIdRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offers': typeof OffersRoute
  '/payment-return': typeof PaymentReturnRoute
  '/settings': typeof SettingsRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/tickets/$packageId': typeof TicketsPackageIdRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/offers': typeof OffersRoute
  '/payment-return': typeof PaymentReturnRoute
  '/settings': typeof SettingsRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/tickets/$packageId': typeof TicketsPackageIdRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offers'
    | '/payment-return'
    | '/settings'
    | '/checkout/$offerId'
    | '/tickets/$packageId'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/offers'
    | '/payment-return'
    | '/settings'
    | '/checkout/$offerId'
    | '/tickets/$packageId'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/offers'
    | '/payment-return'
    | '/settings'
    | '/checkout/$offerId'
    | '/tickets/$packageId'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OffersRoute: typeof OffersRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  SettingsRoute: typeof SettingsRoute
  CheckoutOfferIdRoute: typeof CheckoutOfferIdRoute
  TicketsPackageIdRoute: typeof TicketsPackageIdRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-return': {
      id: '/payment-return'
      path: '/payment-return'
      fullPath: '/payment-return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$packageId': {
      id: '/tickets/$packageId'
      path: '/tickets/$packageId'
      fullPath: '/tickets/$packageId'
      preLoaderRoute: typeof TicketsPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$offerId': {
      id: '/checkout/$offerId'
      path: '/checkout/$offerId'
      fullPath: '/checkout/$offerId'
      preLoaderRoute: typeof CheckoutOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OffersRoute: OffersRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  SettingsRoute: SettingsRoute,
  CheckoutOfferIdRoute: CheckoutOfferIdRoute,
  TicketsPackageIdRoute: TicketsPackageIdRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
